port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: â“ æœªçŸ¥_16
  type: vless
  server: ::ffff:156.238.18.170
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_17
  type: vless
  server: ::ffff:156.238.18.148
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_19
  type: vless
  server: ::ffff:156.238.18.122
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_25
  type: vless
  server: ::ffff:156.238.18.46
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_31
  server: 156.238.18.122
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_34
  server: 156.238.18.191
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_3
  type: vless
  server: ::ffff:156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_4
  type: vless
  server: ::ffff:156.238.18.221
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_42
  server: 156.238.18.153
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_44
  type: vless
  server: ::ffff:156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_7
  type: vless
  server: ::ffff:156.238.18.85
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_59
  type: vless
  server: ::ffff:156.238.18.89
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_9
  type: vless
  server: ::ffff:156.238.18.200
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_67
  server: 156.238.18.66
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬_4
  server: 156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_69
  server: 156.238.18.7
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_72
  server: 156.238.18.172
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_78
  server: 156.238.18.84
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_79
  type: vless
  server: ::ffff:156.238.18.160
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_81
  server: 185.148.104.245
  port: '80'
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
    path: /Telegram:@ShadowProxy66/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_83
  server: 156.238.18.244
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_88
  server: 45.131.4.83
  port: '80'
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
  udp: true
  client-fingerprint: chrome
  servername: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬_6
  type: vless
  server: 156.238.18.199
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_103
  type: vless
  server: ::ffff:156.238.18.203
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_106
  server: 45.142.120.134
  port: '80'
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
    path: /Telegram:@ShadowProxy66/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_108
  server: 156.238.18.85
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_115
  server: 156.238.18.170
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: yd.laoyoutiao.link
    path: /
- type: vless
  name: â“ æœªçŸ¥_118
  server: 45.159.217.86
  port: '80'
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  skip-cert-verify: true
  network: ws
  ws-opts:
    headers:
      Host: ipsycho.suex12.ir
    path: /
  servername: ipsycho.suex12.ir
- type: vless
  name: â“ æœªçŸ¥_123
  server: 104.129.164.39
  port: '8880'
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: ip.langmanshanxi.top
    path: /TelegramğŸ‡¨ğŸ‡³
- type: vless
  name: â“ æœªçŸ¥_130
  server: 141.193.213.26
  port: '80'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /Telegram@WangCai2/?ed
  servername: us.laoyoutiao.link
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_7
  - â“ æœªçŸ¥_44
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_4
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_6
  - â“ æœªçŸ¥_69
  - â“ æœªçŸ¥_17
  - â“ æœªçŸ¥_19
  - â“ æœªçŸ¥_81
  - â“ æœªçŸ¥_123
  - â“ æœªçŸ¥_42
  - â“ æœªçŸ¥_103
  - â“ æœªçŸ¥_67
  - â“ æœªçŸ¥_16
  - â“ æœªçŸ¥_108
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_9
  - â“ æœªçŸ¥_83
  - â“ æœªçŸ¥_106
  - â“ æœªçŸ¥_79
  - â“ æœªçŸ¥_78
  - â“ æœªçŸ¥_88
  - â“ æœªçŸ¥_25
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_3
  - â“ æœªçŸ¥_59
  - â“ æœªçŸ¥_31
  - â“ æœªçŸ¥_130
  - â“ æœªçŸ¥_34
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_4
  - â“ æœªçŸ¥_72
  - â“ æœªçŸ¥_115
  - â“ æœªçŸ¥_118
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
