port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: â“ æœªçŸ¥_8
  type: vless
  server: ::ffff:156.238.18.221
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_13
  server: 156.238.18.221
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_14
  server: 156.238.18.46
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_15
  server: 156.238.18.148
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_18
  type: vless
  server: ::ffff:156.238.18.191
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_21
  server: 156.238.18.191
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_27
  type: vless
  server: ::ffff:156.238.18.170
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_28
  server: 156.238.18.255
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: hysteria2
  name: ğŸ‡ºğŸ‡¸ ç¾å›½_2
  server: 209.141.47.127
  port: '3234'
  password: 65a43b6e-19c5-4fab-b960-d110a07d66a4
  skip-cert-verify: true
  tfo: false
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_37
  server: 156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_48
  type: vless
  server: 156.238.18.207
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_49
  type: vless
  server: ::ffff:156.238.18.58
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_51
  server: 156.238.18.157
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_64
  type: vless
  server: ::ffff:156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_67
  type: vless
  server: 156.238.18.93
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_69
  server: 156.238.18.86
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_74
  server: 156.238.18.153
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_75
  type: vless
  server: 156.238.18.217
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_79
  type: vless
  server: ::ffff:156.238.18.89
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_81
  type: vless
  server: ::ffff:156.238.18.252
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_10
  type: vless
  server: ::ffff:156.238.18.11
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_82
  server: 156.238.18.176
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_83
  server: 156.238.18.177
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_84
  type: vless
  server: ::ffff:156.238.18.232
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_85
  type: vless
  server: ::ffff:156.238.18.88
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_90
  server: 156.238.18.2
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_99
  type: vless
  server: ::ffff:156.238.18.66
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_100
  server: 156.238.18.85
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_115
  server: 5.182.84.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /TelegramU0001F1E8U0001F1F3
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_118
  server: 156.238.18.252
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - ğŸ‡ºğŸ‡¸ ç¾å›½_2
  - â“ æœªçŸ¥_64
  - â“ æœªçŸ¥_82
  - â“ æœªçŸ¥_28
  - â“ æœªçŸ¥_27
  - â“ æœªçŸ¥_18
  - â“ æœªçŸ¥_49
  - â“ æœªçŸ¥_115
  - â“ æœªçŸ¥_15
  - â“ æœªçŸ¥_67
  - â“ æœªçŸ¥_100
  - â“ æœªçŸ¥_69
  - â“ æœªçŸ¥_75
  - â“ æœªçŸ¥_74
  - â“ æœªçŸ¥_8
  - â“ æœªçŸ¥_13
  - â“ æœªçŸ¥_84
  - â“ æœªçŸ¥_83
  - â“ æœªçŸ¥_99
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_10
  - â“ æœªçŸ¥_81
  - â“ æœªçŸ¥_51
  - â“ æœªçŸ¥_79
  - â“ æœªçŸ¥_14
  - â“ æœªçŸ¥_37
  - â“ æœªçŸ¥_48
  - â“ æœªçŸ¥_21
  - â“ æœªçŸ¥_90
  - â“ æœªçŸ¥_118
  - â“ æœªçŸ¥_85
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
