port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: â“ æœªçŸ¥_9
  type: vless
  server: ::ffff:156.238.18.221
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_15
  type: vless
  server: ::ffff:156.238.18.148
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_23
  type: vless
  server: ::ffff:156.238.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_24
  type: vless
  server: ::ffff:156.238.18.54
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_26
  server: 156.238.18.206
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_38
  server: 156.238.18.100
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_4
  server: 156.238.18.175
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_52
  type: vless
  server: 185.148.105.20
  port: '8880'
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  tls: false
  network: ws
  ws-opts:
    path: /Telegram @WangCai2 /?ed=2560
    headers:
      Host: ip.langmanshanxi.top
  servername: ip.langmanshanxi.top
- name: â“ æœªçŸ¥_54
  type: vless
  server: ::ffff:156.238.18.89
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_56
  type: vless
  server: ::ffff:156.238.18.206
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_57
  type: vless
  server: 5.10.214.20
  port: '8880'
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  tls: false
  network: ws
  ws-opts:
    path: /Telegram @WangCai2 /?ed=2560
    headers:
      Host: ip.langmanshanxi.top
  servername: ip.langmanshanxi.top
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_7
  type: vless
  server: ::ffff:156.238.18.175
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_59
  type: vless
  server: ::ffff:156.238.18.85
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_60
  server: 156.238.18.86
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_71
  server: 156.238.18.169
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_76
  type: vless
  server: ::ffff:156.238.18.2
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_77
  server: 156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_79
  type: vless
  server: ::ffff:156.238.18.84
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_81
  type: vless
  server: ::ffff:156.238.18.177
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_88
  type: vless
  server: ::ffff:156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: ğŸ‡«ğŸ‡® èŠ¬å…°_6
  server: 104.21.32.1
  port: '80'
  uuid: 53fa8faf-ba4b-4322-9c69-a3e5b1555049
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: redfree8.redorg1.ir
    path: /?ed=2560
  client-fingerprint: chrome
- type: vless
  name: ğŸ‡ºğŸ‡¸ ç¾å›½_9
  server: 185.251.82.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_97
  type: vless
  server: 147.185.161.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_100
  type: vless
  server: 114.129.43.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_102
  type: vless
  server: 63.141.128.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_104
  server: 147.78.140.20
  port: '8880'
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  udp: true
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_5
  type: vless
  server: 104.129.166.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_108
  server: 91.193.58.175
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_112
  server: 66.235.200.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_116
  type: vless
  server: 104.129.165.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_125
  server: 205.233.181.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_15
  type: vless
  server: 91.193.58.150
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_139
  type: vless
  server: 185.148.105.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_143
  type: vless
  server: 102.177.176.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_159
  type: vless
  server: 135.84.67.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_163
  type: vless
  server: 5.10.215.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_19
  type: vless
  server: 91.193.58.112
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_165
  type: vless
  server: 199.34.230.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_166
  server: 91.193.58.64
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_171
  type: vless
  server: 45.67.215.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_173
  server: 141.193.213.223
  port: '80'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: cs.laoyoutiao.link
    path: /TelegramU0001F1E8U0001F1F3
  client-fingerprint: chrome
  servername: cs.laoyoutiao.link
- name: â“ æœªçŸ¥_174
  type: vless
  server: 89.116.180.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_175
  type: vless
  server: 213.109.205.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_181
  type: vless
  server: 185.207.199.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_182
  type: vless
  server: 45.159.219.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_188
  server: 156.238.18.217
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_189
  type: vless
  server: 45.159.218.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_11
  type: vless
  server: 135.84.75.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_192
  server: 91.193.58.225
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_12
  type: vless
  server: 194.36.55.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_14
  type: vless
  server: 188.164.248.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_22
  type: vless
  server: 156.238.18.76
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: yd.laoyoutiao.link
  disable-sni: true
  skip-cert-verify: true
  client-fingerprint: chrome
  servername: ''
- name: â“ æœªçŸ¥_198
  type: vless
  server: 91.193.58.200
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_200
  type: vless
  server: 102.177.189.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_211
  type: vless
  server: 109.176.239.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡¹ğŸ‡¼ å°æ¹¾_10
  type: vless
  server: 91.193.58.229
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: cs.laoyoutiao.link
  client-fingerprint: chrome
  servername: cs.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_215
  server: 156.238.18.197
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: yd.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: yd.laoyoutiao.link
- name: â“ æœªçŸ¥_225
  type: vless
  server: 91.193.58.247
  port: '8880'
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: steep.skyfigure.top
  client-fingerprint: chrome
  servername: steep.skyfigure.top
- type: vless
  name: â“ æœªçŸ¥_236
  server: 92.53.188.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_238
  server: 45.80.111.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - â“ æœªçŸ¥_77
  - â“ æœªçŸ¥_9
  - â“ æœªçŸ¥_59
  - â“ æœªçŸ¥_24
  - â“ æœªçŸ¥_54
  - â“ æœªçŸ¥_79
  - â“ æœªçŸ¥_15
  - â“ æœªçŸ¥_76
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_7
  - ğŸ‡«ğŸ‡® èŠ¬å…°_6
  - â“ æœªçŸ¥_23
  - â“ æœªçŸ¥_60
  - â“ æœªçŸ¥_171
  - â“ æœªçŸ¥_38
  - â“ æœªçŸ¥_181
  - â“ æœªçŸ¥_26
  - â“ æœªçŸ¥_71
  - â“ æœªçŸ¥_182
  - â“ æœªçŸ¥_100
  - â“ æœªçŸ¥_192
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_4
  - â“ æœªçŸ¥_112
  - â“ æœªçŸ¥_166
  - â“ æœªçŸ¥_143
  - â“ æœªçŸ¥_56
  - â“ æœªçŸ¥_174
  - â“ æœªçŸ¥_102
  - â“ æœªçŸ¥_81
  - ğŸ‡ºğŸ‡¸ ç¾å›½_15
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_11
  - ğŸ‡ºğŸ‡¸ ç¾å›½_22
  - â“ æœªçŸ¥_57
  - â“ æœªçŸ¥_188
  - â“ æœªçŸ¥_211
  - â“ æœªçŸ¥_139
  - â“ æœªçŸ¥_165
  - â“ æœªçŸ¥_108
  - â“ æœªçŸ¥_236
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_12
  - â“ æœªçŸ¥_200
  - â“ æœªçŸ¥_215
  - ğŸ‡ºğŸ‡¸ ç¾å›½_9
  - ğŸ‡ºğŸ‡¸ ç¾å›½_19
  - â“ æœªçŸ¥_104
  - â“ æœªçŸ¥_189
  - â“ æœªçŸ¥_238
  - â“ æœªçŸ¥_52
  - â“ æœªçŸ¥_173
  - â“ æœªçŸ¥_97
  - â“ æœªçŸ¥_198
  - â“ æœªçŸ¥_175
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾_10
  - â“ æœªçŸ¥_88
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_14
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_5
  - â“ æœªçŸ¥_159
  - â“ æœªçŸ¥_125
  - â“ æœªçŸ¥_163
  - â“ æœªçŸ¥_116
  - â“ æœªçŸ¥_225
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
