port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- type: vless
  name: â“ æœªçŸ¥_14
  server: 156.238.18.221
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_16
  server: 156.238.18.46
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_17
  server: 156.238.18.119
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_22
  server: 156.238.18.166
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_23
  type: vless
  server: ::ffff:156.238.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_24
  type: vless
  server: ::ffff:156.238.18.54
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_25
  server: 156.238.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_27
  type: vless
  server: 156.238.18.207
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_41
  server: 156.238.18.85
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_42
  type: vless
  server: ::ffff:156.238.18.207
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_48
  server: 156.238.18.2
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_54
  type: vless
  server: ::ffff:156.238.18.89
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬_4
  server: 156.238.18.132
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_57
  type: vless
  server: 5.10.214.20
  port: '8880'
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  tls: false
  network: ws
  ws-opts:
    path: /Telegram @WangCai2 /?ed=2560
    headers:
      Host: ip.langmanshanxi.top
  servername: ip.langmanshanxi.top
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_7
  type: vless
  server: ::ffff:156.238.18.175
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_64
  server: 156.238.18.190
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_67
  server: 156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_69
  type: vless
  server: ::ffff:156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_71
  server: 156.238.18.169
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_74
  server: 156.238.18.70
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_76
  type: vless
  server: ::ffff:156.238.18.2
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_80
  server: 156.238.18.89
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_81
  type: vless
  server: ::ffff:156.238.18.177
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_8
  type: vless
  server: ::ffff:156.238.18.251
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_89
  server: 156.238.18.176
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_90
  server: 156.238.18.179
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_94
  type: vless
  server: 216.205.52.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: ğŸ‡ºğŸ‡¸ ç¾å›½_9
  server: 185.251.82.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_96
  type: vless
  server: 5.182.85.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_97
  type: vless
  server: 147.185.161.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_105
  type: vless
  server: 5.182.84.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: ğŸ‡ºğŸ‡¸ ç¾å›½_11
  server: 156.238.18.170
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: yd.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: yd.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_5
  type: vless
  server: 104.129.166.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_107
  type: vless
  server: 94.140.0.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_115
  type: vless
  server: 91.193.58.181
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- type: vless
  name: ğŸ‡ºğŸ‡¸ ç¾å›½_14
  server: 91.193.58.245
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_131
  type: vless
  server: 199.34.229.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_15
  type: vless
  server: 91.193.58.150
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_9
  type: vless
  server: 147.185.161.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_135
  type: vless
  server: 45.192.223.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_139
  type: vless
  server: 185.148.105.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_17
  type: vless
  server: 91.193.58.172
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_160
  type: vless
  server: 103.245.229.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_164
  type: vless
  server: 141.193.27.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_166
  server: 91.193.58.64
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_169
  type: vless
  server: 91.193.58.57
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_176
  type: vless
  server: 185.221.160.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_186
  type: vless
  server: 91.193.58.71
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_191
  server: 141.193.213.117
  port: '80'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: cs.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: cs.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_192
  server: 91.193.58.225
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_12
  type: vless
  server: 194.36.55.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_13
  type: vless
  server: 160.153.1.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_193
  server: 216.24.57.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /Telegram@WangCai2/?ed
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_195
  type: vless
  server: 45.159.217.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_22
  type: vless
  server: 156.238.18.76
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: yd.laoyoutiao.link
  disable-sni: true
  skip-cert-verify: true
  client-fingerprint: chrome
  servername: ''
- name: â“ æœªçŸ¥_203
  type: vless
  server: 194.76.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_217
  type: vless
  server: 77.232.140.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_233
  server: 104.16.53.48
  port: '80'
  uuid: c1659206-d827-41f6-9f73-f18ca30102d3
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: still-forest-e3e8-ppal03.mekah93880.workers.dev
    path: /
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_236
  server: 92.53.188.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_239
  server: 91.193.58.184
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - â“ æœªçŸ¥_67
  - â“ æœªçŸ¥_71
  - â“ æœªçŸ¥_74
  - â“ æœªçŸ¥_217
  - â“ æœªçŸ¥_25
  - â“ æœªçŸ¥_76
  - â“ æœªçŸ¥_69
  - â“ æœªçŸ¥_80
  - â“ æœªçŸ¥_54
  - â“ æœªçŸ¥_14
  - â“ æœªçŸ¥_166
  - â“ æœªçŸ¥_186
  - â“ æœªçŸ¥_203
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_7
  - â“ æœªçŸ¥_81
  - â“ æœªçŸ¥_16
  - â“ æœªçŸ¥_96
  - â“ æœªçŸ¥_24
  - â“ æœªçŸ¥_191
  - â“ æœªçŸ¥_41
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_12
  - â“ æœªçŸ¥_89
  - â“ æœªçŸ¥_48
  - â“ æœªçŸ¥_105
  - â“ æœªçŸ¥_64
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_8
  - â“ æœªçŸ¥_23
  - â“ æœªçŸ¥_195
  - â“ æœªçŸ¥_57
  - â“ æœªçŸ¥_169
  - â“ æœªçŸ¥_164
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_9
  - â“ æœªçŸ¥_90
  - â“ æœªçŸ¥_192
  - â“ æœªçŸ¥_27
  - ğŸ‡ºğŸ‡¸ ç¾å›½_11
  - ğŸ‡ºğŸ‡¸ ç¾å›½_15
  - ğŸ‡ºğŸ‡¸ ç¾å›½_22
  - â“ æœªçŸ¥_22
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_4
  - â“ æœªçŸ¥_176
  - â“ æœªçŸ¥_135
  - â“ æœªçŸ¥_107
  - â“ æœªçŸ¥_139
  - â“ æœªçŸ¥_131
  - â“ æœªçŸ¥_42
  - â“ æœªçŸ¥_236
  - â“ æœªçŸ¥_94
  - â“ æœªçŸ¥_115
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_13
  - ğŸ‡ºğŸ‡¸ ç¾å›½_14
  - ğŸ‡ºğŸ‡¸ ç¾å›½_17
  - â“ æœªçŸ¥_17
  - â“ æœªçŸ¥_160
  - â“ æœªçŸ¥_239
  - ğŸ‡ºğŸ‡¸ ç¾å›½_9
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_5
  - â“ æœªçŸ¥_193
  - â“ æœªçŸ¥_97
  - â“ æœªçŸ¥_233
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
