port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: â“ æœªçŸ¥_8
  type: vless
  server: ::ffff:156.238.18.221
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_9
  server: 156.238.18.219
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_15
  server: 156.238.18.148
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_19
  type: vless
  server: 156.238.18.168
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_22
  type: vless
  server: ::ffff:156.238.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_24
  server: 156.238.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_29
  server: 156.238.18.100
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_32
  type: vless
  server: ::ffff:156.238.18.179
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_36
  server: 156.238.18.66
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_37
  server: 156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_40
  type: vless
  server: 5.10.214.20
  port: '8880'
  uuid: 583ceab3-4022-4553-9158-9bedc625ad4e
  tls: false
  network: ws
  ws-opts:
    path: /Telegram @WangCai2 /?ed=2560
    headers:
      Host: ip.langmanshanxi.top
  client-fingerprint: chrome
  servername: ip.langmanshanxi.top
- type: vless
  name: â“ æœªçŸ¥_41
  server: 156.238.18.132
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_44
  type: vless
  server: ::ffff:156.238.18.104
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_45
  server: 156.238.18.190
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_49
  type: vless
  server: ::ffff:156.238.18.58
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_52
  server: 156.238.18.94
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_58
  server: 156.238.18.169
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_60
  server: 156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_61
  server: 156.238.18.179
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_64
  type: vless
  server: ::ffff:156.238.18.224
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_70
  type: vless
  server: ::ffff:156.238.18.2
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_74
  server: 156.238.18.153
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- name: â“ æœªçŸ¥_76
  type: vless
  server: ::ffff:156.238.18.131
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_78
  type: vless
  server: ::ffff:156.238.18.169
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_86
  type: vless
  server: ::ffff:156.238.18.70
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_90
  server: 156.238.18.2
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_91
  type: vless
  server: ::ffff:156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬_2
  type: vless
  server: 156.238.18.98
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_100
  server: 156.238.18.85
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_114
  server: 156.238.18.78
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - â“ æœªçŸ¥_45
  - â“ æœªçŸ¥_61
  - â“ æœªçŸ¥_60
  - â“ æœªçŸ¥_74
  - â“ æœªçŸ¥_64
  - â“ æœªçŸ¥_8
  - â“ æœªçŸ¥_19
  - â“ æœªçŸ¥_78
  - â“ æœªçŸ¥_32
  - â“ æœªçŸ¥_86
  - â“ æœªçŸ¥_22
  - â“ æœªçŸ¥_70
  - â“ æœªçŸ¥_37
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_2
  - â“ æœªçŸ¥_52
  - â“ æœªçŸ¥_58
  - â“ æœªçŸ¥_100
  - â“ æœªçŸ¥_49
  - â“ æœªçŸ¥_29
  - â“ æœªçŸ¥_76
  - â“ æœªçŸ¥_36
  - â“ æœªçŸ¥_24
  - â“ æœªçŸ¥_41
  - â“ æœªçŸ¥_91
  - â“ æœªçŸ¥_90
  - â“ æœªçŸ¥_15
  - â“ æœªçŸ¥_40
  - â“ æœªçŸ¥_44
  - â“ æœªçŸ¥_114
  - â“ æœªçŸ¥_9
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
