port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- name: â“ æœªçŸ¥_17
  type: vless
  server: ::ffff:156.238.18.148
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_24
  server: 156.238.18.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_25
  type: vless
  server: ::ffff:156.238.18.46
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_28
  type: vless
  server: ::ffff:156.238.18.54
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_33
  type: vless
  server: ::ffff:156.238.18.179
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_6
  type: vless
  server: ::ffff:156.238.18.123
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_51
  type: vless
  server: ::ffff:156.238.18.244
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_57
  server: 156.238.18.190
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_67
  server: 156.238.18.66
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_69
  server: 156.238.18.7
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_75
  type: vless
  server: ::ffff:156.238.18.222
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_97
  server: 45.159.216.208
  port: '80'
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
    path: /Telegram:@ShadowProxy66/?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_125
  server: 91.193.58.116
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sk.laoyoutiao.link
    path: /TelegramU0001F1E8U0001F1F3
  servername: sk.laoyoutiao.link
- name: AE_speednode_0001
  server: 94.140.0.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: AE_speednode_0004
  server: 103.245.228.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: AU_speednode_0016
  server: 103.169.142.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: CA_speednode_0023
  server: 74.49.215.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: CY_speednode_0041
  server: 213.109.205.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: FR_speednode_0071
  server: 141.11.203.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: GB_speednode_0081
  server: 104.239.72.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: NL_speednode_0120
  server: 45.131.7.191
  port: 80
  type: vless
  uuid: 89b3cbba-e6ac-485a-9481-976a0415eab9
  tls: false
  skip-cert-verify: false
  servername: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
  network: ws
  ws-opts:
    path: /Telegram:@ShadowProxy66/?ed=2560
    headers:
      Host: uuhUHYygEsdFGH.UYHJHGvgFcjGUJhbUIlbVFDxDxM.xyz
  udp: true
- name: NL_speednode_0133
  server: 45.131.209.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: RU_speednode_0153
  server: 193.233.132.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: RU_speednode_0161
  server: 31.12.75.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: RU_speednode_0165
  server: 185.148.107.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: US_speednode_0202
  server: 45.159.217.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: US_speednode_0229
  server: 141.193.27.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: US_speednode_0237
  server: 159.242.242.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: US_speednode_0238
  server: 170.114.45.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
- name: ZA_speednode_0280
  server: 102.177.176.213
  port: 8880
  type: vless
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
  network: ws
  ws-opts:
    path: /?ed=2560
    headers:
      Host: jp.laoyoutiao.link
  udp: true
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - â“ æœªçŸ¥_51
  - â“ æœªçŸ¥_25
  - RU_speednode_0165
  - â“ æœªçŸ¥_75
  - â“ æœªçŸ¥_28
  - US_speednode_0202
  - â“ æœªçŸ¥_97
  - US_speednode_0229
  - â“ æœªçŸ¥_33
  - FR_speednode_0071
  - RU_speednode_0161
  - â“ æœªçŸ¥_67
  - â“ æœªçŸ¥_69
  - GB_speednode_0081
  - â“ æœªçŸ¥_57
  - ZA_speednode_0280
  - CY_speednode_0041
  - â“ æœªçŸ¥_17
  - RU_speednode_0153
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_6
  - AE_speednode_0001
  - AE_speednode_0004
  - US_speednode_0238
  - AU_speednode_0016
  - CA_speednode_0023
  - NL_speednode_0120
  - â“ æœªçŸ¥_125
  - NL_speednode_0133
  - US_speednode_0237
  - â“ æœªçŸ¥_24
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
