port: 7890
socks-port: 7891
redir-port: 7892
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090
geodata-mode: true
geox-url:
  geoip: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/geoip.dat
  mmdb: https://slink.ltd/https://raw.githubusercontent.com/Loyalsoldier/geoip/release/GeoLite2-Country.mmdb
dns:
  enable: true
  ipv6: false
  default-nameserver:
  - 223.5.5.5
  - 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  fallback:
  - https://doh.dns.sb/dns-query
  - https://dns.cloudflare.com/dns-query
  - https://dns.twnic.tw/dns-query
  - tls://8.8.4.4:853
  fallback-filter:
    geoip: true
    ipcidr:
    - 240.0.0.0/4
    - 0.0.0.0/32
proxies:
- type: vless
  name: â“ æœªçŸ¥_16
  server: 156.238.18.46
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_28
  type: vless
  server: ::ffff:156.238.18.122
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- name: â“ æœªçŸ¥_32
  type: vless
  server: ::ffff:156.238.18.255
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_34
  server: 156.238.18.11
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_36
  type: vless
  server: ::ffff:156.238.18.166
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: ğŸ‡«ğŸ‡® èŠ¬å…°_2
  server: 141.193.213.225
  port: '2086'
  uuid: 7fed5bf9-a1de-41a0-ab89-694265c4895f
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: domain2025.dpdns.org
    path: /@vpnAndroid2.@vpnAndroid2.@vpnAndroid2.@vpnAndroid2?ed=2560
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_42
  type: vless
  server: ::ffff:156.238.18.207
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_46
  server: 156.238.18.172
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- type: vless
  name: ğŸ‡«ğŸ‡® èŠ¬å…°_3
  server: 45.131.4.235
  port: '2086'
  uuid: 7fed5bf9-a1de-41a0-ab89-694265c4895f
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: domain2025.dpdns.org
    path: /@vpnAndroid2.@vpnAndroid2.@vpnAndroid2.@vpnAndroid2?ed=2560
  client-fingerprint: chrome
- type: vless
  name: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_4
  server: 156.238.18.175
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_53
  type: vless
  server: ::ffff:156.238.18.160
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬_4
  server: 156.238.18.132
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_61
  server: 156.238.18.94
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: sg.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2048
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_62
  type: vless
  server: ::ffff:156.238.18.203
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /Telegram@WangCai2/?ed=2048
    headers:
      Host: sg.laoyoutiao.link
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_77
  server: 156.238.18.212
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: jp.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_83
  server: 156.238.18.131
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /TelegramğŸ‡¨ğŸ‡³@WangCai2/?ed=2560
  client-fingerprint: chrome
  servername: sg.laoyoutiao.link
- type: vless
  name: ğŸ‡ºğŸ‡¸ ç¾å›½_6
  server: 188.42.89.53
  port: '2086'
  uuid: 7fed5bf9-a1de-41a0-ab89-694265c4895f
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: domain2025.dpdns.org
    path: /@vpnAndroid2.@vpnAndroid2.@vpnAndroid2.@vpnAndroid2?ed=2560
  client-fingerprint: chrome
- type: vless
  name: â“ æœªçŸ¥_85
  server: 156.238.18.142
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: jp.laoyoutiao.link
    path: /Telegram@WangCai2/?ed=2560
  client-fingerprint: chrome
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_3
  type: vless
  server: 5.182.34.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_94
  type: vless
  server: 216.205.52.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_98
  type: vless
  server: 91.193.58.79
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_106
  server: 5.182.84.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_107
  type: vless
  server: 94.140.0.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_6
  type: vless
  server: 185.174.138.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_109
  type: vless
  server: 103.116.7.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_110
  type: vless
  server: 192.65.217.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_115
  type: vless
  server: 91.193.58.181
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_127
  type: vless
  server: 167.68.5.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_131
  type: vless
  server: 199.34.229.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: ğŸ‡­ğŸ‡° é¦™æ¸¯_8
  server: 66.45.118.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /
  client-fingerprint: chrome
- name: â“ æœªçŸ¥_136
  type: vless
  server: 176.124.223.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_139
  type: vless
  server: 185.148.105.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_140
  type: vless
  server: 91.193.58.104
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_143
  type: vless
  server: 102.177.176.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_144
  type: vless
  server: 161.145.150.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_145
  type: vless
  server: 170.114.46.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_17
  type: vless
  server: 91.193.58.172
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_158
  type: vless
  server: 66.81.247.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_160
  type: vless
  server: 103.245.229.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_164
  type: vless
  server: 141.193.27.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_165
  type: vless
  server: 199.34.230.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_167
  server: 103.169.142.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: hk.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_168
  type: vless
  server: 88.216.69.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_173
  server: 141.193.213.223
  port: '80'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: cs.laoyoutiao.link
    path: /TelegramU0001F1E8U0001F1F3
  client-fingerprint: chrome
  servername: cs.laoyoutiao.link
- name: â“ æœªçŸ¥_175
  type: vless
  server: 213.109.205.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: â“ æœªçŸ¥_180
  type: vless
  server: 92.53.190.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: ğŸ‡¹ğŸ‡¼ å°æ¹¾_8
  server: 91.193.58.69
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: cs.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: cs.laoyoutiao.link
- name: â“ æœªçŸ¥_187
  type: vless
  server: 108.165.152.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_11
  type: vless
  server: 135.84.75.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_191
  server: 141.193.213.117
  port: '80'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: cs.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: cs.laoyoutiao.link
- name: ğŸ‡­ğŸ‡° é¦™æ¸¯_13
  type: vless
  server: 160.153.1.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_21
  type: vless
  server: 91.193.58.18
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_193
  server: 216.24.57.20
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: us.laoyoutiao.link
    path: /Telegram@WangCai2/?ed
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_196
  type: vless
  server: 168.100.6.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- name: ğŸ‡ºğŸ‡¸ ç¾å›½_22
  type: vless
  server: 156.238.18.76
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: yd.laoyoutiao.link
  disable-sni: true
  skip-cert-verify: true
  client-fingerprint: chrome
  servername: ''
- name: â“ æœªçŸ¥_198
  type: vless
  server: 91.193.58.200
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: us.laoyoutiao.link
  client-fingerprint: chrome
  servername: us.laoyoutiao.link
- name: â“ æœªçŸ¥_211
  type: vless
  server: 109.176.239.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
- type: vless
  name: â“ æœªçŸ¥_215
  server: 156.238.18.197
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  skip-cert-verify: false
  network: ws
  ws-opts:
    headers:
      Host: yd.laoyoutiao.link
    path: /
  client-fingerprint: chrome
  servername: yd.laoyoutiao.link
- name: â“ æœªçŸ¥_225
  type: vless
  server: 91.193.58.247
  port: '8880'
  uuid: 63601f9f-7c67-4952-919a-1ef802b5a7ec
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: steep.skyfigure.top
  client-fingerprint: chrome
  servername: steep.skyfigure.top
- name: â“ æœªçŸ¥_234
  type: vless
  server: 160.79.105.29
  port: '8880'
  uuid: fab7bf9c-ddb9-4563-8a04-fb01ce6c0fbf
  tls: false
  network: ws
  ws-opts:
    path: /
    headers:
      Host: hk.laoyoutiao.link
  client-fingerprint: chrome
  servername: hk.laoyoutiao.link
proxy-groups:
- name: èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - è‡ªåŠ¨é€‰æ‹©
  - æ•…éšœè½¬ç§»
  - DIRECT
  - æ‰‹åŠ¨é€‰æ‹©
- name: è‡ªåŠ¨é€‰æ‹©
  type: url-test
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: &id001
  - â“ æœªçŸ¥_53
  - ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡_4
  - â“ æœªçŸ¥_16
  - ğŸ‡«ğŸ‡® èŠ¬å…°_2
  - â“ æœªçŸ¥_61
  - â“ æœªçŸ¥_83
  - ğŸ‡«ğŸ‡® èŠ¬å…°_3
  - â“ æœªçŸ¥_85
  - â“ æœªçŸ¥_28
  - â“ æœªçŸ¥_34
  - â“ æœªçŸ¥_46
  - â“ æœªçŸ¥_32
  - â“ æœªçŸ¥_196
  - ğŸ‡ºğŸ‡¸ ç¾å›½_6
  - â“ æœªçŸ¥_167
  - â“ æœªçŸ¥_62
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_6
  - â“ æœªçŸ¥_165
  - â“ æœªçŸ¥_94
  - â“ æœªçŸ¥_180
  - â“ æœªçŸ¥_145
  - ğŸ‡ºğŸ‡¸ ç¾å›½_21
  - â“ æœªçŸ¥_160
  - â“ æœªçŸ¥_143
  - ğŸ‡ºğŸ‡¸ ç¾å›½_22
  - â“ æœªçŸ¥_215
  - â“ æœªçŸ¥_110
  - â“ æœªçŸ¥_107
  - â“ æœªçŸ¥_36
  - â“ æœªçŸ¥_42
  - â“ æœªçŸ¥_106
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_13
  - â“ æœªçŸ¥_127
  - ğŸ‡ºğŸ‡¸ ç¾å›½_17
  - â“ æœªçŸ¥_139
  - â“ æœªçŸ¥_136
  - â“ æœªçŸ¥_168
  - â“ æœªçŸ¥_211
  - â“ æœªçŸ¥_164
  - â“ æœªçŸ¥_193
  - â“ æœªçŸ¥_77
  - â“ æœªçŸ¥_175
  - â“ æœªçŸ¥_234
  - â“ æœªçŸ¥_187
  - â“ æœªçŸ¥_115
  - â“ æœªçŸ¥_173
  - â“ æœªçŸ¥_131
  - â“ æœªçŸ¥_158
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_3
  - â“ æœªçŸ¥_140
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_8
  - â“ æœªçŸ¥_109
  - ğŸ‡­ğŸ‡° é¦™æ¸¯_11
  - â“ æœªçŸ¥_98
  - â“ æœªçŸ¥_198
  - â“ æœªçŸ¥_191
  - ğŸ‡¹ğŸ‡¼ å°æ¹¾_8
  - â“ æœªçŸ¥_144
  - ğŸ‡¯ğŸ‡µ æ—¥æœ¬_4
  - â“ æœªçŸ¥_225
  url: http://www.pinterest.com
  interval: 300
  tolerance: 50
- name: æ•…éšœè½¬ç§»
  type: fallback
  exclude-filter: (?i)ä¸­å›½|China|CN|ç”µä¿¡|ç§»åŠ¨|è”é€š
  proxies: *id001
  url: http://www.gstatic.com/generate_204
  interval: 300
- name: æ‰‹åŠ¨é€‰æ‹©
  type: select
  proxies: *id001
rules:
- DOMAIN,app.adjust.com,DIRECT
- GEOIP,CN,DIRECT
- MATCH,èŠ‚ç‚¹é€‰æ‹©
